public enum PlaneStates {
    AWAITING_LANDING_PERMISSION,
    AWAITING_RUNAWAY_LANDING,
    LANDING,
    DOCKING,
    UNLOADING_PASSENGERS,
    GETTING_CLEANED,
    REFILLING_SUPPLIES,
    AWAITING_REFUEL_TRUCK,
    REFUELING_TANK,
    LOADING_PASSENGERS,
    UNDOCKING,
    AWAITING_RUNAWAY_TAKEOFF,
    TAKING_OFF,
    FINISHED
}
